### ISSUE TITLE
Problem of Compatible version

### ISSUE THREAD

**Issue by medfrk** [affise/sdk-react#1]
I want to integrate in my react native mobile app: when i install affiche/sdk-react with  yarn add affise-attribution-lib and after pod install it give me this error:
[!] CocoaPods could not find compatible versions for pod "AffiseAttributionLib":
  In Podfile:
    affise-attribution-native (from `../node_modules/affise-attribution-lib`) was resolved to 1.1.6, which depends on
      AffiseAttributionLib (~> 1.1.5)

None of your spec sources contain a spec satisfying the dependency: `AffiseAttributionLib (~> 1.1.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by skornei** [comment]
**Can't reproduce you're error.**

CocoaPods [AffiseAttributionLib 1.1.5 is available](https://github.com/CocoaPods/Specs/blob/master/Specs/a/9/3/AffiseAttributionLib/1.1.5/AffiseAttributionLib.podspec.json)

Try to create empty project

```console
npx react-native@latest init AwesomeProject
npm install affise-attribution-lib
# yarn add affise-attribution-lib
cd ios
pod install
cd ..
# setup affise attribution
npx react-native start
npx react-native run-ios
```

Or use [this simple AwesomeProject.zip](https://github.com/affise/sdk-react/files/11510606/AwesomeProject.zip) 
_There was no issue with building and launching it._

```console
yarn
cd ios
pod install
cd ..
yarn ios
```

Make sure there are no spaces in project path

Try to open you're project workspace `ios/<YourProject>.xcworkspace` and run from xcode
